### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by rugk** [cketti/ShareUrlToClipboard#1]
Can you please publish this on F-Droid?

It seems to be useful as an alternative to the other "copy to clipboard" apps as one might only want to get the URL. (You should describe this advantage in the app's description. 😃)

**Comment by cketti** [comment]
This is just a sample app to demonstrate how apps with Share functionality can add an extra item to the chooser dialog. It's not an app that offers a generic "copy URL to clipboard" Share target.

**Comment by cketti** [comment]
The [blog post](http://cketti.de/2016/06/15/share-url-to-clipboard/) linked in the README describes all this.

**Comment by rugk** [comment]
Ah, sorry, I just read it:
> All you need is an app that hooks into the Share dialog and then extracts links from the text shared to it. Writing such an app is easy enough and will be the topic of a future post.

So you will publish this app? 😺
